name: App CI
on:
  push:
    paths:
      - 'services/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        working-directory: services/routing
        run: |
          docker build -t revops-routing:ci .
